import express from 'express';
import { cancelOrder, checkCoupons, createACoupon, createANewOrder, trackOrder, updateOrder} from '../controller/userController.js';
import { getAllUsers } from '../controller/userController.js';
import { deleteUser } from '../controller/userController.js';
import { validateToken } from '../validateToken.js';
import { createPdfAndEmail} from '../controller/mailerController.js';
const route = express.Router();
route.post("/create-order",createANewOrder);
route.get("/orders",validateToken, getAllUsers);
route.delete("/delete-order/:id",deleteUser);
route.post('/send-email',createPdfAndEmail);
route.put('/update-status',cancelOrder);
route.post('/order-status',trackOrder);
route.put('/change-status',updateOrder);
route.post('/coupon/create',createACoupon);
route.post('/coupon/validate',checkCoupons);
export default route;